#!/bin/sh

# Setup for GI-GTK Nyxt to look descent in Gnome
# Sym Linked to -> /usr/bin/

# Set title bar of GTK applications 
export GTK_THEME=Adwaita:dark

# Launch Nyxt in the background
exec /home/logoraz/common-lisp/nyxt/nyxt
